---
title: 'Tema 6: Datos multidimensionales'
author: "Alonso Pizarro Lagunas"
date: "28/10/2021"
output:
  html_document: default
  pdf_document: default
---

# Datos Multidimenionales


## Ejemplo con tres dimensiones

```{r tresvariables}
ans = sample(c("Si","No"), size= 100, replace = T)
sex = sample(c("H","M"), size = 100, replace = T)
place = sample(c("San Francisco", "Barcelona", "Valencia", "Cobija", "Asturias"), size = 100, replace = T)

table(sex, ans, place)

ftable(sex,ans,place)  # tabla en formato plano
ftable(sex, ans, place, col.vars =c("sex", "ans")) 
```


### Filtrar las tablas

```{r filtrados}

table(sex,ans,place)['M','Si','San Francisco']
table(sex, ans, place)[ , 'Si', 'Valencia']
table(sex, ans, place)[ , 'No', ]
table(sex,ans,place)['M', ,'Cobija']
```


### Frecuencias relativas


```{r freqrelativas}
prop.table(table(sex,ans,place)) # frec.relativas globales
prop.table(table(sex,ans,place), margin = 3) # frec. relativa por lugar
prop.table(table(sex,ans,place), margin = c(1,3)) # frec relativa por sexo y país
ftable(prop.table(table(sex,ans,place))) # formato plano
```


?gmodels





