---
title: "R & Python"
author: "Alonso Pizarro Lagunas"
date: "13/10/2021"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Reticulate

```{r reticulate}
library(reticulate)
use_python("/Users/sept/anaconda3/python.exe, required =TRUE")

# py_install("Nombre del paquete a insytalar")


os <- import("os")
os$listdir(".")
```

```{r}
source_python("add.py")
add(3,4)
```


```{r}
np <- import("numpy", convert = FALSE)

x <- np$array(c(1:4))
sum <- x$cumsum()

print(sum)

## si quiero convertir al el resultado a formato ## r

py_to_r(sum)



```


## Ayuda

```{r}
#help(py_to_r)
#py_help(os$chdir)
```

## Arrays

```{r}
a <- np_array(c(1:10), order= "C")
a
```

```{r}
datos <- iris
head(datos)


datos_py <- r_to_py(datos)
```


```{python}
import numpy as np
import pandas as pd
r.datos_py.head
```

```{r}
library(Matrix)
N <- 6
set.seed(123)
sparse_mat <- sparseMatrix(
  i = sample(N,N, replace = FALSE),
  j = sample(N,N, replace = FALSE),
  x = runif(N),
  dims = c(N,N))


sparse_mat

sparse_mat_py <- r_to_py(sparse_mat)

```


```{python}
r.sparse_mat_py
```


